### ISSUE TITLE
ak.txt

### ISSUE THREAD

**Issue by WWz33** [zhangrengang/subgenome_phasing_example#3]
张老师您好！
非常感谢这么详细的教程给我学习的机会
请教一下，在配置文件中的`ancestor_left = ak.txt`这个文件是如何生成的呢，我可以直接设置为none么？

**Comment by zhangrengang** [comment]
不是自动生成的。参考这个文件，手工做一个参考基因组的核型文件，就改下第一列的染色体编号和第三列的基因数目。然后其他基因组的核型就通过-km映射过去。-km时不能设置为none。

**Comment by WWz33** [comment]
非常感谢张老师的耐心解答
